/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ci.server;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        ContinuousIntegrationServer.startServer();
    }
}
